server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjnbit_bbs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
logging:
  level:
    com.zjnbit.bbs: debug
